language: go
go:
#         - 1.5.x
#         - 1.6.x
#         - 1.7.x
        - 1.10.x
        - 1.11.x
        - 1.12.x
        - 1.13.x
        - 1.14.x
        - 1.15.x
before_install:
        # - go get github.com/mattn/goveralls   # code coverage tracking
        - go get -t -v ./...                  # grab project dependencies (non-vendor)
install:
        # - 
before_script:
        - gofmt -d -s .                       # gofmt code so it's pretty
        - go vet ./...                        # some lint-type checking
script:
        # - go test -v -race ./...            # run go tests
        # - $HOME/gopath/bin/goveralls -service=travis-ci   # run code coverage
        - cd splunk/
        - go build
